# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "deployment/*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "deployment/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VUE_APP_RUN_ID: ${{ github.run_id }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - name: tar dist
        run: tar -czvf dist.tar.gz dist/
      - name: head commit hash use to make a release and message
        run: |
          GITHUB_SHA_SHORT=$( echo '${{ github.event.head_commit.id }}' | cut -c-7 )
          echo "commit_hash:" $GITHUB_SHA_SHORT
          RELEASE_TAG=$(date '+%Y%m%d%H%M%S')-$GITHUB_SHA_SHORT
          echo release tag: $RELEASE_TAG
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
      - name: make a relase with commit hash
        uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.gz
          tag_name: ${{ env.RELEASE_TAG }}
